### ISSUE TITLE
App crash 

### ISSUE THREAD

**Issue by AbdulSalamAli0018** [thoughtbot/expandable-recycler-view#133]
I have launched the sample on my 6.0 device and the app crashes stated the following error 

`java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
                                                                                                       at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:514)
                                                                                                       at android.support.v7.widget.DefaultItemAnimator.animateAdd(DefaultItemAnimator.java:217)
                                                                                                       at android.support.v7.widget.SimpleItemAnimator.animateAppearance(SimpleItemAnimator.java:114)
                                                                                                       at android.support.v7.widget.RecyclerView.animateAppearance(RecyclerView.java:3243)
                                                                                                       at android.support.v7.widget.RecyclerView.access$800(RecyclerView.java:147)
                                                                                                       at android.support.v7.widget.RecyclerView$4.processAppeared(RecyclerView.java:436)
                                                                                                       at android.support.v7.widget.ViewInfoStore.process(ViewInfoStore.java:249)
                                                                                                       at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3098)
                                                                                                       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                                                                       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1080)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1742)
                                                                                                       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
                                                                                                       at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:344)
                                                                                                       at android.widget.FrameLayout.onLayout(FrameLayout.java:281)
                                                                                                       at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:3175)
                                                                                                       at android.view.View.layout(View.java:18010)
                                                                                                       at android.view.ViewGroup.layout(ViewGroup.java:5911)
                                                                                                       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2784)
                                                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2477)
                                                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)
                                                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7616)
                                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:622)
                                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                                                       at android.app.ActivityThread.main(ActivityThread.java:7406)
                                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper"`

**Comment by andremachado35** [comment]
add this too gradle app 
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.0'
            }
        }
    }
}
