### ISSUE TITLE
java.lang.RuntimeException: Unknown state

### ISSUE THREAD

**Issue by Devspm** [thoughtbot/expandable-recycler-view#152]
Hi , I got this error suddenly when i try to collapse the recyclerview.

`java.lang.RuntimeException: Unknown state
        at com.thoughtbot.expandablerecyclerview.models.ExpandableList.getUnflattenedPosition(ExpandableList.java:79)
        at com.thoughtbot.expandablerecyclerview.ExpandableRecyclerViewAdapter.getItemViewType(ExpandableRecyclerViewAdapter.java:105)
        at com.arjinmc.recyclerviewdecoration.RecyclerViewItemDecoration.getItemOffsets(RecyclerViewItemDecoration.java:185)
        at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:4792)
        at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:8981)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1585)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3763)
        at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3219)
        at android.view.View.measure(View.java:18788)
        at android.widget.RelativeLayout.measureChild(RelativeLayout.java:676)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:479)
        at android.view.View.measure(View.java:18788)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
        at android.view.View.measure(View.java:18788)`

**Comment by mirjalal** [comment]
```
@Override
public int getItemCount() {
    return super.getItemCount(); // I wrote like this, not myElementList().size()
}
```

What did you write in your `getItemCount()` method? See #29 and #30 .
