### ISSUE TITLE
onGroupExpanded bug

### ISSUE THREAD

**Issue by darienalvarez** [thoughtbot/expandable-recycler-view#29]
when the child list of every group is empty you will get:

` java.lang.RuntimeException: Unknown state
                                                                                 at com.thoughtbot.expandablerecyclerview.models.ExpandableList.getUnflattenedPosition(ExpandableList.java:80)
                                                                                 at com.thoughtbot.expandablerecyclerview.ExpandableRecyclerViewAdapter.onGroupExpanded(ExpandableRecyclerViewAdapter.java:119)
                                                                                 at com.thoughtbot.expandablerecyclerview.ExpandCollapseController.expandGroup(ExpandCollapseController.java:44)
                                                                                 at com.thoughtbot.expandablerecyclerview.ExpandCollapseController.toggleGroup(ExpandCollapseController.java:77)
                                                                                 at com.thoughtbot.expandablerecyclerview.ExpandableRecyclerViewAdapter.onGroupClick(ExpandableRecyclerViewAdapter.java:151)
                                                                                 at com.thoughtbot.expandablerecyclerview.viewholders.GroupViewHolder.onClick(GroupViewHolder.java:28)
                                                                                 at android.view.View.performClick(View.java:4881)
                                                                                 at android.view.View$PerformClick.run(View.java:19592)
                                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:146)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5756)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                                 at dalvik.system.NativeStart.main(Native Method)`

when you try to expand the last group item

**Comment by mandybess** [comment]
@darienalvarez thanks for bringing this up. I fixed it in #30 and will merge and release soon
