### ISSUE TITLE
Calling adapter.toggleGroup sometimes leads to Crash

### ISSUE THREAD

**Issue by nimaaaaw** [thoughtbot/expandable-recycler-view#79]
Hi,
I am trying to create the functionality that collapses all other groups when one is expanded.
so I wrote this code :
`adapter.setOnGroupExpandCollapseListener(new GroupExpandCollapseListener() {
            @Override
            public void onGroupExpanded(final ExpandableGroup group) {
                new Handler().postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        for (int i = 0; i < adapter.getGroups().size(); i++) {
                            if (categories.get(i).getId() != ((Category) group).getId()) {
                                if (adapter.isGroupExpanded(adapter.getGroups().get(i))) {
                                    adapter.toggleGroup(adapter.getGroups().get(i));
                                }
                            }
                        }
                    }
                }, 100);
            }
            @Override
            public void onGroupCollapsed(ExpandableGroup group) {
            }
        });`

everything is working fine but sometimes (in my case when I have 3 groups, and click on first group when 3rd one is expanded) I get Exceptions for Inconsistency Detected.
`Process: com.tagisland.tagisland.tagisland_native_android, PID: 31402
                                                                                                  java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2d9fcc34 position=11 id=-1, oldPos=4, pLpos:4 scrap [attachedScrap] tmpDetached not recyclable(1) no parent}
                                                                                                      at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5297)
                                                                                                      at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5479)
                                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                                      at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                                      at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                                                      at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                                                      at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                                                      at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:595)
                                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3534)
                                                                                                      at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3310)
                                                                                                      at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1190)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1190)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.support.v7.widget.LinearLayoutCompat.setChildFrame(LinearLayoutCompat.java:1645)
                                                                                                      at android.support.v7.widget.LinearLayoutCompat.layoutVertical(LinearLayoutCompat.java:1499)
                                                                                                      at android.support.v7.widget.LinearLayoutCompat.onLayout(LinearLayoutCompat.java:1407)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1167)
                                                                                                      at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:852)
                                                                                                      at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:871)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1954)
                                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1808)
                                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1717)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1954)
                                                                                                      at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1808)
                                                                                                      at android.widget.LinearLayout.onLayout(LinearLayout.java:1717)
                                                                                                      at android.view.View.layout(View.java:15991)
                                                                                                      at android.view.ViewGroup.layout(ViewGroup.java:5118)
                                                                                                      at android.widget.FrameLayout.layoutChildren(FrameLayout.java:628)
                                                                                                      at android.widget.FrameLayout.onLayout(FrameLayout.java:563)
                                                                                                      at android.view.View.layout(View.java:15991)`

**Comment by ericmguimaraes** [comment]
Happened for me too :(

**Comment by alfco333** [comment]
I have the same issue when trying to collapse all groups.

**Comment by rajsuvariya** [comment]
Please go through https://github.com/thoughtbot/expandable-recycler-view/issues/54#issuecomment-284171806 and try to relate it with your issue if it helps

**Comment by diogo10** [comment]
Same issue here guys, any sulutions?

The comment 54 doesn't work @rajsuvariya.

**Comment by zedxer** [comment]
its 2019 any update on this issue?
